# Colors (Gruvbox Material Medium Dark)

# Default colors
[colors.primary]
background = '#282828'
# foreground = '#d4be98'
foreground = '#e2cca9'

# Normal colors
[colors.normal]
black   = '#3c3836'
red     = '#ea6962'
# orange  = '#e78a4e'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#3c3836'
red     = '#ea6962'
# orange  = '#e78a4e'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
