[general]
  import = ["~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"]

[colors]
  draw_bold_text_with_bright_colors = true

[keyboard]
  bindings = [
    # { key = "n", mods = "Command|Shift", action = "SpawnNewInstance" },
    { key = "Tab", mods = "Control", action = "SelectNextTab" },
    { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" }
  ]

[mouse]
  hide_when_typing = true

[window]
  dimensions = { columns = 128, lines = 44 }
  padding = { x = 5, y = 5 }
  dynamic_padding = true
  dynamic_title = true
  # decorations = "None"
  # decorations = "Transparent"
  decorations = "Buttonless"
  # opacity = 0.975
  opacity = 1.0
  # blur = true
  blur = false
  resize_increments = true

[font]
  size = 12.0
  # size = 22.0
  offset.x = 0  # For letter spacing (default: 0)
  offset.y = 0  # For line spacing (default: 0)

[font.normal]
  family="TX-02"
  # family="Berkeley Mono"
  # family="CommitMono-450-01111-00000011000"
  style="Regular"

[font.bold]
  family="TX-02"
  # family="Berkeley Mono"
  # family="CommitMono-450-01111-00000011000"
  style="Bold"

[font.italic]
  family="TX-02"
  # family="Berkeley Mono"
  # family="CommitMono-450-01111-00000011000"
  style="Oblique"

[font.bold_italic]
  family="TX-02"
  # family="Berkeley Mono"
  # family="CommitMono-450-01111-00000011000"
  style="Bold-Oblique"

[[hints.enabled]]
command = ""
hyperlinks = true
mouse.enabled = false
